name: Java CI

on: [push]

jobs:
  build:
    name: Build with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['11', '17']

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.jdk }}
          cache: 'gradle'

      - name: Gradle Check
        run: ./gradlew build check
