name: Java CI

on: [push]

jobs:
  build:
    name: Build with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['1.8', '9', '10', '11', '12', '13', '14']

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Gradle Check
        run: ./gradlew build check