name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  build:
    name: Build with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['17', '21', '23'] # Gradle doesn't support JDK 24 yet

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: ${{ matrix.jdk }}
          cache: 'gradle'

      - name: Gradle Check
        run: ./gradlew build check
